### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by SkinnyDevOps** [nicolassing/NicolassingQuillBundle#3]
Hi,
I have a problem with the installation in an existing project. The problem is with dependencies. Below is a message from composer:
php composer.phar require nicolassing/quill-bundle
Using version ^1.0 for nicolassing/quill-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "^5.0"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove doctrine/doctrine-bundle 2.1.2
    - Conclusion: don't install doctrine/doctrine-bundle 2.1.2
    - twig/twig v2.0.0 conflicts with doctrine/doctrine-bundle[2.1.2].
    - twig/twig v2.1.0 conflicts with doctrine/doctrine-bundle[2.1.2].
    - twig/twig v2.2.0 conflicts with doctrine/doctrine-bundle[2.1.2].
    - twig/twig v2.3.0 conflicts with doctrine/doctrine-bundle[2.1.2].
    - twig/twig v2.3.1 conflicts with doctrine/doctrine-bundle[2.1.2].
    - twig/twig v2.3.2 conflicts with doctrine/doctrine-bundle[2.1.2].
    - Installation request for doctrine/doctrine-bundle (locked at 2.1.2) -> satisfiable by doctrine/doctrine-bundle[2.1.2].
    - Installation request for nicolassing/quill-bundle ^1.0 -> satisfiable by nicolassing/quill-bundle[v1.0].
    - Conclusion: don't install twig/twig v3.0.5|install twig/twig v2.0.0|install twig/twig v2.1.0|install twig/twig v2.2.0|install twig/twig v2.3.0|install twig/twig v2.3.1|install twig/twig v2.3.2
    - Conclusion: remove twig/twig v3.0.5|install twig/twig v2.0.0|install twig/twig v2.1.0|install twig/twig v2.2.0|install twig/twig v2.3.0|install twig/twig v2.3.1|install twig/twig v2.3.2
    - nicolassing/quill-bundle v1.0 requires twig/twig ^2.0 -> satisfiable by twig/twig[v2.0.0, v2.1.0, v2.10.0, v2.11.0, v2.11.1, v2.11.2, v2.11.3, v2.12.0, v2.12.1, v2.12.2, v2.12.3, v2.12.4, v2.12.5, v2.13.0, v2.13.1, v2.2.0, v2.3.0, v2.3.1, v2.3.2, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.5.0, v2.6.0, v2.6.1, v2.6.2, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.8.0, v2.8.1, v2.9.0].
    - Can only install one of: twig/twig[v2.10.0, v3.0.5].
    - Can only install one of: twig/twig[v2.11.0, v3.0.5].
    - Can only install one of: twig/twig[v2.11.1, v3.0.5].
    - Can only install one of: twig/twig[v2.11.2, v3.0.5].
    - Can only install one of: twig/twig[v2.11.3, v3.0.5].
    - Can only install one of: twig/twig[v2.12.0, v3.0.5].
    - Can only install one of: twig/twig[v2.12.1, v3.0.5].
    - Can only install one of: twig/twig[v2.12.2, v3.0.5].
    - Can only install one of: twig/twig[v2.12.3, v3.0.5].
    - Can only install one of: twig/twig[v2.12.4, v3.0.5].
    - Can only install one of: twig/twig[v2.12.5, v3.0.5].
    - Can only install one of: twig/twig[v2.13.0, v3.0.5].
    - Can only install one of: twig/twig[v2.13.1, v3.0.5].
    - Can only install one of: twig/twig[v2.4.0, v3.0.5].
    - Can only install one of: twig/twig[v2.4.1, v3.0.5].
    - Can only install one of: twig/twig[v2.4.2, v3.0.5].
    - Can only install one of: twig/twig[v2.4.3, v3.0.5].
    - Can only install one of: twig/twig[v2.4.4, v3.0.5].
    - Can only install one of: twig/twig[v2.4.5, v3.0.5].
    - Can only install one of: twig/twig[v2.4.6, v3.0.5].
    - Can only install one of: twig/twig[v2.4.7, v3.0.5].
    - Can only install one of: twig/twig[v2.4.8, v3.0.5].
    - Can only install one of: twig/twig[v2.5.0, v3.0.5].
    - Can only install one of: twig/twig[v2.6.0, v3.0.5].
    - Can only install one of: twig/twig[v2.6.1, v3.0.5].
    - Can only install one of: twig/twig[v2.6.2, v3.0.5].
    - Can only install one of: twig/twig[v2.7.0, v3.0.5].
    - Can only install one of: twig/twig[v2.7.1, v3.0.5].
    - Can only install one of: twig/twig[v2.7.2, v3.0.5].
    - Can only install one of: twig/twig[v2.7.3, v3.0.5].
    - Can only install one of: twig/twig[v2.7.4, v3.0.5].
    - Can only install one of: twig/twig[v2.8.0, v3.0.5].
    - Can only install one of: twig/twig[v2.8.1, v3.0.5].
    - Can only install one of: twig/twig[v2.9.0, v3.0.5].
    - Installation request for twig/twig (locked at v3.0.5) -> satisfiable by twig/twig[v3.0.5].
Installation failed, reverting ./composer.json to its original content.

My composer.json file:
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "doctrine/annotations": "^1.8",
        "laminas/laminas-code": "^3.4",
        "laminas/laminas-eventmanager": "^3.3",
        "ramsey/uuid": "^4.0",
        "ramsey/uuid-doctrine": "^1.6",
        "sensio/framework-extra-bundle": "^5.5",
        "symfony/apache-pack": "^1.0",
        "symfony/asset": "^5.0",
        "symfony/console": "^5.0",
        "symfony/doctrine-bridge": "^5.0",
        "symfony/dotenv": "^5.0",
        "symfony/flex": "^1.3.1",
        "symfony/form": "^5.0",
        "symfony/framework-bundle": "^5.0",
        "symfony/orm-pack": "^1.0",
        "symfony/security-bundle": "^5.0",
        "symfony/translation": "^5.0",
        "symfony/twig-pack": "^1.0",
        "symfony/validator": "^5.0",
        "symfony/yaml": "^5.0"
    },
    "require-dev": {
        "sensiolabs/security-checker": "^6.0",
        "symfony/maker-bundle": "^1.14",
        "symfony/profiler-pack": "^1.0",
        "symfony/var-dumper": "^5.0"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd",
            "security-checker security:check": "script"
        },
        "auto-scripts-dev": {
            "security-checker security:check": "script"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "^5.0"
        }
    }
}

When I add this repo to composer.json and make clean install I have an error:
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 216:
!!                                                                            
!!    The child node "theme" at path "nicolassing_quill" must be configured.  
!!                                                                            
!!  
!!  
Script @auto-scripts was called via post-update-cmd

How can I fix this ?

**Comment by nicolassing** [comment]
Hello, 
I added support for Twig >=3.0 !
Can you retry and tell me if everything is ok ? 
Thx !

**Comment by SkinnyDevOps** [comment]
Hello,
I repeat install and I get this:

php composer.phar require nicolassing/quill-bundle
Using version ^1.1 for nicolassing/quill-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Restricting packages listed in "symfony/symfony" to "5.1.*"
Package operations: 2 installs, 0 updates, 0 removals
  - Installing symfony/templating (v5.1.5): Loading from cache
  - Installing nicolassing/quill-bundle (v1.1): Downloading (100%)         
Writing lock file
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
96 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Symfony operations: 1 recipe (d49b10095d7424ccf8232758649f1483)
  - Configuring nicolassing/quill-bundle (>=v1.1): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 216:
!!                                                                            
!!    The child node "theme" at path "nicolassing_quill" must be configured.  
!!                                                                            
!!  
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content.

**Comment by nicolassing** [comment]
you have to configure the bundle in `config/packages/nicolassing_quill.yaml`

```yaml
nicolassing_quill:
    theme: snow
    height: 10rem
```

**Comment by nicolassing** [comment]
I close this one. 

Do not hesitate to reopen if you need :)
